$:
  tag_push:
    - services:
        - docker
      docker:
        image: node:24
      runner:
        network: idc
      stages:
        - name: 安装依赖
          script: npm install
        - name: 构建项目
          script: npm run build
        - name: 配置npm官方源
          script: npm config set registry https://registry.npmjs.org
        - name: 配置token
          imports: https://git.woa.com/qq-ai/web/secret/blob/master/envs/npm/npmjs.txt
          script: npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN
        - name: 设置npm包版本号
          script: npm version ${ORANGE_BRANCH} --no-git-tag-version --allow-same-version
        - name: 发布npm包
          script: npm publish
        - name: make message
          script: echo "npm包版本${ORANGE_BRANCH}推送成功" > message.txt
        - name: send message
          type: wework:message
          options:
            fromFile: message.txt
